apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "db_credentials"   # This must match the secret name in AWS Secrets Manager
        objectType: "secretsmanager"
