name: Infinity Pool CI/CD
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: infinity-pool-eks
  RELEASE_NAME: infinity-pool
  TERRAFORM_VERSION: 1.11.1
  TERRAGRUNT_VERSION: 0.75.4
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/**'
      - '**/docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/**'
      - '**/docs/**'

jobs:
  lint:
    name: Lint and Static Analysis
    if: github.event.before != '0000000000000000000000000000000000000000'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      # Install the latest version of Terraform CLI and configure the Terraform CLI
      # configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      # Initialize a new or existing Terraform working directory by creating initial files,
      # loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check
      # Terraform linting and validation
      - name: Terraform Validate
        run: terraform validate
      # Helm linting
      #- name: Lint Helm Chart
      #  run: helm lint ./helm

  deploy-infra:
    name: Deploy the Infrastructure
    if: github.event.before != '0000000000000000000000000000000000000000'
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      # Configure AWS Credentials. See: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true
      - name: Set AWS Account ID
        run: echo AWS_ACCOUNT_ID=${{ steps.aws-credentials.outputs.aws-account-id}} >> $GITHUB_ENV
      #  https://github.com/gruntwork-io/terragrunt-action
      - name: Run Terragrunt Plan
        uses: gruntwork-io/terragrunt-action@v2.1.5
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: terragrunt
          tg_command: plan
      - name: Run Terragrunt Apply
        uses: gruntwork-io/terragrunt-action@v2.1.5
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: terragrunt
          tg_command: apply

  deploy-services:
    name: Deploy Infinity Pool Services
    if: github.event.before != '0000000000000000000000000000000000000000'
    needs: [ deploy-infra ]
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Configure AWS Credentials. See: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Set AWS Account ID
        run: echo AWS_ACCOUNT_ID=${{ steps.aws-credentials.outputs.aws-account-id}} >> $GITHUB_ENV

      # Login to ECR. See: https://github.com/aws-actions/amazon-ecr-login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # BACKEND SERVICE
      - name: Build, tag, and push BACKEND docker image to Amazon ECR
        working-directory: app/backend
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: infinity-pool
          BACKEND_IMAGE_TAG: backend-${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$BACKEND_IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$BACKEND_IMAGE_TAG

      # GATEWAY SERVICE
      - name: Build, tag, and push GATEWAY docker image to Amazon ECR
        working-directory: app/gateway
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: infinity-pool
          GATEWAY_IMAGE_TAG: gateway-${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$GATEWAY_IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$GATEWAY_IMAGE_TAG

      # RUN HELM
      # See: https://github.com/marketplace/actions/deploy-helm-chart-to-aws-eks-cluster
      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
        env:
          BACKEND_IMAGE_TAG: backend-${{ github.sha }}
          GATEWAY_IMAGE_TAG: gateway-${{ github.sha }}
          REPOSITORY: infinity-pool
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          chart-path: helm/
          namespace: default
          values: |
            aws.accountId=${{ env.AWS_ACCOUNT_ID }},
            aws.region=${{ env.AWS_REGION }},
            gateway.image.repository=${{ env.REPOSITORY }},
            gateway.image.tag=${{ env.GATEWAY_IMAGE_TAG }},
            backend.image.repository=${{ env.REPOSITORY }},
            backend.image.tag=${{ env.BACKEND_IMAGE_TAG }}
          name: ${{ env.RELEASE_NAME }}